Add ShoppingCart model
dmarmul/book-shop pull request #10
Opened 2024-10-17 20:35 UTC by dmarmul

Added ShoppingCart and CartItem models, mappers, Dtos, service, repositories and controller for adding CartItem to ShoppingCart, update, delete and show items.

2024-10-18 09:40 UTC, ahoienko requested changes
Good job! Please check comments

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/controller/CartController.java
> +
```suggestion

```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/controller/CartController.java
> +    }
```suggestion
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/controller/CartController.java
> +    public CartItemDto add(@RequestBody @Valid CreateCartRequestDto requestDto) {
```suggestion
    public CartItemDto add(@RequestBody @Valid CreateCartRequestDto requestDto, @AuthenticationPrincipal User user) {
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/controller/CartController.java
> +        return cartService.add(requestDto, userName);
```suggestion
        return cartService.add(requestDto, user);
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/dto/CartDto.java
> +public class CartDto {
```suggestion
public class ShoppingCartDto {
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/mapper/ShoppingCartMapper.java
> +@Mapper(config = MapperConfig.class)
```suggestion
@Mapper(config = MapperConfig.class, uses = CartItemMapper.class)
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/mapper/ShoppingCartMapper.java
> +    }
```suggestion

```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/model/CartItem.java
> +    @Min(1)
```suggestion
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/model/CartItem.java
> +    @Column(nullable = false)
Please make fetch type Lazy

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/controller/CartController.java
> +    public CartDto getAll() {
```suggestion
    public CartDto get() {
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +    public CartDto findAll(String username) {
```suggestion
    public CartDto get(String username) {
```

2024-10-18 09:40 UTC, ahoienko commented on src/main/java/org/example/bookshop/dto/CreateCartRequestDto.java
> +public class CreateCartRequestDto {
```suggestion
public class CartItemRequestDto {
```

2024-10-18 19:04 UTC, Elena-Bruyako requested changes
see comments

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/controller/CartController.java
> +    public CartItemDto add(@RequestBody @Valid CartItemRequestDto requestDto,
```suggestion
    public ShoppingCartDto add(@RequestBody @Valid CartItemRequestDto requestDto,
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/controller/CartController.java
> +    public CartItemDto update(@RequestBody @Valid CartUpdateRequestDto requestDto,
```suggestion
    public ShoppingCartDto update(@RequestBody @Valid CartUpdateRequestDto requestDto,
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/dto/CartItemRequestDto.java
> +    @NotNull
int type can't be null
```suggestion
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/dto/CartItemRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/dto/CartItemRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/dto/CartUpdateRequestDto.java
> +    @Min(1)
```suggestion
    @Positive
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/CartItem.java
> +    @JoinColumn(name = "shopping_cart_id")
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "shopping_cart_id", nullable = false)
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/CartItem.java
> +    @ManyToOne
```suggestion
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "book_id", nullable = false)
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/CartItem.java
> +@ToString
```suggestion
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/ShoppingCart.java
> +@ToString
ToString leads to exception in such entities
```suggestion
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/ShoppingCart.java
> +    @OneToOne(fetch = FetchType.LAZY)
```suggestion
    @MapsId
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "id", nullable = false)
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/model/ShoppingCart.java
> +    @OneToMany(mappedBy = "shoppingCart")
```suggestion
    @OneToMany(mappedBy = "shoppingCart", cascade = CascadeType.ALL, orphanRemoval = true)
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/repository/CartRepository.java
> +    @NonNull
```suggestion
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +    public CartItemDto add(CartItemRequestDto requestDto, User user) {
```suggestion
    public ShoppingCartDto add(CartItemRequestDto requestDto, User user) {
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +    public CartItemDto update(CartUpdateRequestDto requestDto, Long id, User user) {
```suggestion
    public ShoppingCartDto update(CartUpdateRequestDto requestDto, Long id, User user) {
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +                "Can't found cartRepository for user :" + user.getEmail())
```suggestion
                "Can't find cartRepository for user :" + user.getEmail())
```

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +        if (findCartItemById(findShoppingCart(user), id) != null) {
it's not readable
find shop cart `findByUserId`
find cartItem `findByIdAndShoppingCartId`

remove cartItem

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +public class CartServiceImpl implements CartService {
Think where `@Transactional` is needed

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +        CartItem cartItem = cartItemMapper.toCartItem(requestDto);
it's better to find book, find shop cart, check if cart already include the same book, if yes - increment quantity, if no - add book to cart

It's better to save shop cart at the end of method

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/UserServiceImpl.java
> +        ShoppingCart shoppingCart = new ShoppingCart();
create method `createShoppingCart(User user)` in ShopCartService and implement the logic

2024-10-18 19:04 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/UserServiceImpl.java
> +        user = userRepository.save(user);
```suggestion
        userRepository.save(user);
```

2024-10-19 19:03 UTC, Elena-Bruyako requested changes
see comments

2024-10-19 19:03 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/UserServiceImpl.java
> +        cartService.createShoppingCart(userRepository.save(user));
```suggestion
        userRepository.save(user)
        cartService.createShoppingCart(user);
```

2024-10-19 19:03 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +    @Transactional
```suggestion
```

2024-10-19 19:03 UTC, Elena-Bruyako commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +        cartRepository.save(shoppingCart);
```suggestion
        shoppingCart.setUser(user);
        cartRepository.save(shoppingCart);
```

2024-10-20 10:25 UTC, okuzan approved these changes

2024-10-20 10:25 UTC, okuzan commented on src/main/java/org/example/bookshop/dto/CartItemDto.java
> +@Setter
Not a mistake but FYI it's ok to use @Data from lombok on DTOs, just not JPA entities

2024-10-20 10:25 UTC, okuzan commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +        }
```suggestion
        if (cartItemRepository.findByIdAndUserId(id, user.getId()).isEmpty()) {
            throw new EntityNotFoundException("Can't find cartItem by id: " + id);
        }
        cartItemRepository.deleteById(id);
```

2024-10-20 10:25 UTC, okuzan commented on src/main/java/org/example/bookshop/service/impl/CartServiceImpl.java
> +        }
we don't need else after returning throwing, so in such cases, to simplify the code, invert if condition

2024-10-20 13:39 UTC, merged